//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.FreestyleCastCrewEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.FreestyleCastCrewEdit.ActionTexts", typeof(ActionTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Divider.
        /// </summary>
        internal static string AddDivider {
            get {
                return ResourceManager.GetString("AddDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Value.
        /// </summary>
        internal static string ChangeValue {
            get {
                return ResourceManager.GetString("ChangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Grid.
        /// </summary>
        internal static string ClearGrid {
            get {
                return ResourceManager.GetString("ClearGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Grids.
        /// </summary>
        internal static string ClearGrids {
            get {
                return ResourceManager.GetString("ClearGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Names.
        /// </summary>
        internal static string CopyNames {
            get {
                return ResourceManager.GetString("CopyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Row(s).
        /// </summary>
        internal static string CutRows {
            get {
                return ResourceManager.GetString("CutRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter Episode Name here].
        /// </summary>
        internal static string EnterEpisodeNameHere {
            get {
                return ResourceManager.GetString("EnterEpisodeNameHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter Group Name here].
        /// </summary>
        internal static string EnterGroupNameHere {
            get {
                return ResourceManager.GetString("EnterGroupNameHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Grid.
        /// </summary>
        internal static string InitializeGrid {
            get {
                return ResourceManager.GetString("InitializeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row.
        /// </summary>
        internal static string InsertRow {
            get {
                return ResourceManager.GetString("InsertRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Row.
        /// </summary>
        internal static string MoveRow {
            get {
                return ResourceManager.GetString("MoveRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from Clipboard.
        /// </summary>
        internal static string PasteFromClipboard {
            get {
                return ResourceManager.GetString("PasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo {0}.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Row(s).
        /// </summary>
        internal static string RemoveRows {
            get {
                return ResourceManager.GetString("RemoveRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default Values.
        /// </summary>
        internal static string SetDefaultValues {
            get {
                return ResourceManager.GetString("SetDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Crew.
        /// </summary>
        internal static string SortCrew {
            get {
                return ResourceManager.GetString("SortCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Grid.
        /// </summary>
        internal static string Sorted {
            get {
                return ResourceManager.GetString("Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo {0}.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
