//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.FreestyleCastCrewEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBoxTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.FreestyleCastCrewEdit.MessageBoxTexts", typeof(MessageBoxTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: The Birth Year is no number (Row: {1})..
        /// </summary>
        internal static string BirthYearIsNoNumber {
            get {
                return ResourceManager.GetString("BirthYearIsNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast &amp; Crew Data will be emptied. Continue?.
        /// </summary>
        internal static string CastCrewEmptyData {
            get {
                return ResourceManager.GetString("CastCrewEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clipboard data can&apos;t be read. Make sure it contains valid Cast data..
        /// </summary>
        internal static string CastDataCantBeRead {
            get {
                return ResourceManager.GetString("CastDataCantBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Data will be emptied. Continue?.
        /// </summary>
        internal static string CastEmptyData {
            get {
                return ResourceManager.GetString("CastEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Data will be overwritten. Continue?.
        /// </summary>
        internal static string CastOverwriteData {
            get {
                return ResourceManager.GetString("CastOverwriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The check was successful..
        /// </summary>
        internal static string CheckOk {
            get {
                return ResourceManager.GetString("CheckOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard operation failed. Please try again..
        /// </summary>
        internal static string ClipboardOperationFailed {
            get {
                return ResourceManager.GetString("ClipboardOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be empty (Row: {1})..
        /// </summary>
        internal static string ColumnMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ColumnMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clipboard data can&apos;t be read. Make sure it contains valid Crew data..
        /// </summary>
        internal static string CrewDataCantBeRead {
            get {
                return ResourceManager.GetString("CrewDataCantBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew Data will be emptied. Continue?.
        /// </summary>
        internal static string CrewEmptyData {
            get {
                return ResourceManager.GetString("CrewEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew Data will be overwritten. Continue?.
        /// </summary>
        internal static string CrewOverwriteData {
            get {
                return ResourceManager.GetString("CrewOverwriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///A log file was created under &quot;{1}&quot;. Please send it to profiler_plugins@doena-soft.de.de..
        /// </summary>
        internal static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error!.
        /// </summary>
        internal static string CriticalErrorHeader {
            get {
                return ResourceManager.GetString("CriticalErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Group section &quot;{0}&quot; contains a different Category (&quot;{1}&quot;) than the Group Start divider (&quot;{2}&quot;) (Row: {3})..
        /// </summary>
        internal static string DifferentCreditTypesCrewMember {
            get {
                return ResourceManager.GetString("DifferentCreditTypesCrewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Group section &quot;{0}&quot; ends with a different Category (&quot;{1}&quot;) than the Group Start divider (&quot;{2}&quot;) (Row: {3})..
        /// </summary>
        internal static string DifferentCreditTypesEndDivider {
            get {
                return ResourceManager.GetString("DifferentCreditTypesEndDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; can&apos;t be read..
        /// </summary>
        internal static string FileCantBeRead {
            get {
                return ResourceManager.GetString("FileCantBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; can&apos;t be written..
        /// </summary>
        internal static string FileCantBeWritten {
            get {
                return ResourceManager.GetString("FileCantBeWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstNameColumn {
            get {
                return ResourceManager.GetString("FirstNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: You have a Group End divider with no previous Group Start divider (Row: {1})..
        /// </summary>
        internal static string GroupEndDivider {
            get {
                return ResourceManager.GetString("GroupEndDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found for &apos;{0}&apos;..
        /// </summary>
        internal static string NoMatchFound {
            get {
                return ResourceManager.GetString("NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not select any rows..
        /// </summary>
        internal static string NoRowsSelected {
            get {
                return ResourceManager.GetString("NoRowsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string WarningHeader {
            get {
                return ResourceManager.GetString("WarningHeader", resourceCulture);
            }
        }
    }
}
